/// One row per package type (14 rows). Source: Warehouse Package Type.xlsx.
/// Only 4 of the 14 appear in Sales (Each, Pair, Packet, Bag), and "Each"
/// accounts for 97% of turnover - so this is a weak analytical dimension, but
/// assignment task 5 asks for quantity and sales by package type.
table 'Package Type'

	/// Source column: PackageTypeID.
	column 'Package Type ID'
		dataType: int64
		formatString: 0
		isHidden
		sourceColumn: Package Type ID
		summarizeBy: none

	/// Source column: PackageTypeName.
	column 'Package Type'
		dataType: string
		sourceColumn: Package Type
		summarizeBy: none

	partition 'Package Type' = m
		mode: import
		source =
				let
					Source = Excel.Workbook(File.Contents(SourceFolderPath & "Warehouse Package Type.xlsx"), null, true),
					Sheet = Source{[Item = "Sheet1", Kind = "Sheet"]}[Data],
					PromotedHeaders = Table.PromoteHeaders(Sheet, [PromoteAllScalars = true]),
					RenamedColumns = Table.RenameColumns(PromotedHeaders, {
						{"PackageTypeID", "Package Type ID"},
						{"PackageTypeName", "Package Type"}
					}),
					TypedColumns = Table.TransformColumnTypes(RenamedColumns, {
						{"Package Type ID", Int64.Type},
						{"Package Type", type text}
					}),
					Result = TypedColumns
				in
					Result

	annotation PBI_ResultType = Table

