/// One row per order line (212,774 rows).
/// Source: dss_demos.bi_tasks.sales, which is a pre-joined flattening of order
/// header, order line, invoice and customer transaction. Only the
/// order-line-grain columns are loaded - see the partition comments and
/// docs/decisions/0002.
table 'Sales'

	/// Source column: OrderID. Degenerate dimension - 67,628 distinct values.
	/// Drives the "unique order count" KPI via [Order Count].
	column 'Order ID'
		dataType: int64
		formatString: 0
		sourceColumn: Order ID
		summarizeBy: none

	/// Source column: OrderLineID. Primary key of the fact table - unique
	/// across all 212,774 rows.
	column 'Order Line ID'
		dataType: int64
		formatString: 0
		isHidden
		sourceColumn: Order Line ID
		summarizeBy: none

	/// Source column: CustomerID. Foreign key to Customer.
	column 'Customer ID'
		dataType: int64
		formatString: 0
		isHidden
		sourceColumn: Customer ID
		summarizeBy: none

	/// Source column: StockItemID. Foreign key to Product.
	column 'Stock Item ID'
		dataType: int64
		formatString: 0
		isHidden
		sourceColumn: Stock Item ID
		summarizeBy: none

	/// Source column: SupplierID. Foreign key to Supplier. Fully derivable
	/// from StockItemID (identical on all 212,774 rows) but kept as a direct
	/// fact-to-dimension key to keep the star flat - see docs/decisions/0006.
	column 'Supplier ID'
		dataType: int64
		formatString: 0
		isHidden
		sourceColumn: Supplier ID
		summarizeBy: none

	/// Source column: PackageTypeID. Foreign key to Package Type. Equals
	/// StockItem.UnitPackageID on all 212,774 rows (not OuterPackageID), so it
	/// is the *unit* package. Kept direct - see docs/decisions/0006.
	column 'Package Type ID'
		dataType: int64
		formatString: 0
		isHidden
		sourceColumn: Package Type ID
		summarizeBy: none

	/// Source column: OrderDate, parsed from text ("Tuesday, January 1, 2013").
	/// The single analytical date of this model; relates to Date.
	column 'Order Date'
		dataType: dateTime
		formatString: dd/MM/yyyy
		isHidden
		sourceColumn: Order Date
		summarizeBy: none

	/// Source column: Quantity. Units ordered on this line.
	column Quantity
		dataType: int64
		formatString: #,0
		isHidden
		sourceColumn: Quantity
		summarizeBy: sum

	/// Source column: PickedQuantity. Units actually picked; differs from
	/// Quantity on 2,710 lines.
	column 'Picked Quantity'
		dataType: int64
		formatString: #,0
		isHidden
		sourceColumn: Picked Quantity
		summarizeBy: sum

	/// Source column: UnitPrice, parsed from currency-formatted text via
	/// fnParseMoney. Price per unit, ex-tax. Non-additive, so it never
	/// auto-aggregates.
	column 'Unit Price'
		dataType: decimal
		formatString: "£"#,0.00
		sourceColumn: Unit Price
		summarizeBy: none

	/// Source column: TaxRate, parsed from percent-formatted text ("10.00%" /
	/// "15.00%") back to 0.10 / 0.15. Non-additive.
	column 'Tax Rate'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		sourceColumn: Tax Rate
		summarizeBy: none

	/// Quantity * Unit Price, computed in Power Query. This is the model's
	/// definition of sales (ex-tax, order-line grain) per
	/// docs/decisions/0002. Aggregate it only through [Total Sales].
	column 'Line Amount'
		dataType: decimal
		formatString: "£"#,0.00
		isHidden
		sourceColumn: Line Amount
		summarizeBy: sum

	/// TRUE when the source row carried an InvoiceID. FALSE on 2,857 lines
	/// belonging to 2,809 orders that were never invoiced. Those lines are
	/// included in every sales figure - see docs/decisions/0003.
	column 'Is Invoiced'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceColumn: Is Invoiced
		summarizeBy: none

	partition 'Sales' = m
		mode: import
		source =
				let
					Source = DatabricksBiTasks{[Name = "sales", Kind = "Table"]}[Data],
					// Columns deliberately not loaded, none of which any KPI
					// needs: AmountExcludingTax / TaxAmount / TransactionAmount
					// (invoice grain repeated on every line - summing them here
					// overstates sales 3.69x, see docs/decisions/0002);
					// IsUndersupplyBackordered (constant "Yes"); InvoiceDate /
					// TransactionDate / FinalizationDate (all derivable from each
					// other); the five person IDs and ConfirmedReceivedBy (no
					// lookup table supplied); PickingCompletedWhen and
					// ConfirmedDeliveryTime (contain timestamps);
					// ExpectedDeliveryDate, BackorderOrderID, BillToCustomerID,
					// CustomerPurchaseOrderNumber, TotalDryItems,
					// CustomerTransactionID.
					//
					// Columns are picked by name. The .xlsx extract could not do
					// that: it carried three columns all literally headed
					// "UnitPrice" (currency text, always empty, and numeric), so
					// promoting its header row would have collided, and the query
					// had to keep Excel's Column1..Column35 names and pick by
					// position. The warehouse table has 33 uniquely named columns -
					// the two redundant UnitPrice copies are not there at all - so
					// the positional workaround is gone, and a column reordering
					// upstream can no longer silently load the wrong data.
					SelectedColumns = Table.SelectColumns(Source, {
						"OrderID",
						"CustomerID",
						"OrderDate",
						"OrderLineID",
						"StockItemID",
						"PackageTypeID",
						"Quantity",
						"UnitPrice",
						"TaxRate",
						"PickedQuantity",
						"InvoiceID",
						"SupplierID"
					}),
					RenamedColumns = Table.RenameColumns(SelectedColumns, {
						{"OrderID", "Order ID"},
						{"CustomerID", "Customer ID"},
						{"OrderDate", "Order Date"},
						{"OrderLineID", "Order Line ID"},
						{"StockItemID", "Stock Item ID"},
						{"PackageTypeID", "Package Type ID"},
						{"UnitPrice", "Unit Price"},
						{"TaxRate", "Tax Rate"},
						{"PickedQuantity", "Picked Quantity"},
						{"InvoiceID", "Invoice ID"},
						{"SupplierID", "Supplier ID"}
					}),
					// OrderDate arrives as text in US long-date form
					// ("Tuesday, January 1, 2013"). The culture is stated
					// explicitly so the parse does not depend on the machine's
					// regional settings.
					ParsedOrderDate = Table.TransformColumns(RenamedColumns, {
						{"Order Date", each Date.FromText(_, [Format = "dddd, MMMM d, yyyy", Culture = "en-US"]), type date}
					}),
					// Both of these arrive as formatted text from the warehouse
					// where the .xlsx extract had a numeric copy to lean on:
					//   UnitPrice  "?13.00"  ->  13    (see fnParseMoney)
					//   TaxRate    "15.00%"  ->  0.15
					// Only two distinct tax rates exist in the source, 10.00% and
					// 15.00%, and both were verified to parse on all 212,774 rows.
					ParsedAmounts = Table.TransformColumns(ParsedOrderDate, {
						{"Unit Price", fnParseMoney, type nullable number},
						{"Tax Rate", each Number.FromText(Text.Remove(_, {"%"}), "en-US") / 100, type number}
					}),
					TypedColumns = Table.TransformColumnTypes(ParsedAmounts, {
						{"Order ID", Int64.Type},
						{"Customer ID", Int64.Type},
						{"Order Line ID", Int64.Type},
						{"Stock Item ID", Int64.Type},
						{"Package Type ID", Int64.Type},
						{"Quantity", Int64.Type},
						{"Unit Price", Currency.Type},
						{"Tax Rate", type number},
						{"Picked Quantity", Int64.Type},
						{"Supplier ID", Int64.Type}
					}),
					// The model's sales definition. Computed here rather than as
					// a DAX calculated column, per the team's Power Query-first
					// rule for calculated columns.
					AddedLineAmount = Table.AddColumn(TypedColumns, "Line Amount", each [Quantity] * [Unit Price], Currency.Type),
					// Invoice ID itself is not loaded (64,819 distinct values on
					// 212,774 rows costs RAM for no KPI); the boolean flag is
					// all the uninvoiced-orders analysis needs.
					AddedIsInvoiced = Table.AddColumn(AddedLineAmount, "Is Invoiced", each [Invoice ID] <> null, type logical),
					RemovedInvoiceID = Table.RemoveColumns(AddedIsInvoiced, {"Invoice ID"}),
					Result = RemovedInvoiceID
				in
					Result

	annotation PBI_ResultType = Table

